### ISSUE TITLE
Fetch and POST Data in the Dashboard

### ISSUE THREAD

**Issue by nuhafadh** [mahzumy/PennyWise#7]
- [x] Fetch Data from Transaction Table
- [x] Fetch Data from User Table (for User Section above)
- [x] Post Data for new record / transaction

**Comment by ahmadadam12** [comment]
ini harus buat UI nya sekalian kah?

**Comment by ahmadadam12** [comment]
ini harus buat UI nya sekalia kah?

**Comment by mahzumy** [comment]
gak mas, UI dibautkan issue sendiri saja
